Add instructions for preparing a power cut
cms-gem-daq-project/sw_utils pull request #12
Opened 2018-11-21 22:11 UTC by lpetre-ulb

Add the instructions for preparing a power cut as it was done at ULB on 19 November 2018.

Also add precisions about the recovery from a power cut. Some services must run on the DAQ machine and AMC's must be out of extraction mode.

## Description

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context
We might need to safely power off a GEM stand in case of a planned power cut.

## How Has This Been Tested?

### Screenshots (if appropriate):

## Checklist:
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-11-22 10:36 UTC, bdorney commented on v3ElectronicsUserGuide.md
> +     - Ensure that the `sysmgr`, `xinetd` and `dnsmasq` services are correctly started. You can use the `systemctl status <service name> command to check each service status. The `Active` field must
you're missing the closing ` here, e.g. you have:

```
`systemctl status <service name>
```

Should be 

```
`systemctl status <service name>`
```

2018-11-22 10:37 UTC, bdorney commented on v3ElectronicsUserGuide.md
> +In order to safely prepare a GEM test stand before a planned power cut execute:
Should be:

> In order to safely prepare a GEM test stand for a planned power cut execute:

e.g. change "before" for "for"

2018-11-22 10:38 UTC, bdorney commented on v3ElectronicsUserGuide.md
> +     - Use the opportunity to power down other sensitive equipement such as PMT's.
Change to:

> Use the opportunity to power down other sensitive equipment, such as PMT's.

E.g. insert a comma after "equipment" and correct typo, e.g. equipment (correct) vs. equipement (wrong)

2018-11-22 10:38 UTC, bdorney commented on v3ElectronicsUserGuide.md
> +     - Gently pull the hot swap tab on the AMC's (CTP7 and AMC13). Wait until the blue LED stays on solid on each AMC's.
Change " on the AMC's (CTP7 and AMC13)" to "on all AMC's including the AMC13" as some users might be using GLIBs.

2018-11-22 10:40 UTC, bdorney commented on v3ElectronicsUserGuide.md
> + 5. Power down the µTCA crate Power Modules one at a time. If powered with AC/DC converters, simply flip the switch on the AC/DC one at a time.
All crates will be powered with an AC/DC converter.  The converter supplies the voltage to the PM.  The difference is some manufacturers provide crates with built in converters (e.g. VadaTech) while others require an external converter (e.g. Schroff).  Try to clarify this point.

2018-11-22 10:41 UTC, bdorney commented on v3ElectronicsUserGuide.md
> +     - Push the hot swap tabs on the AMC's and wait for the blue LED's to turn off.
Change line 764 go:

> Push the hot swap tabs on the AMC's, including the AMC13, and wait for the blue LED's to turn off.

2018-11-22 10:42 UTC, bdorney requested changes
Slight grammatical changes needed.  Otherwise good.

2018-11-22 23:28 UTC, lpetre-ulb commented
Grammatical changes done.

2018-11-23 11:57 UTC, bdorney approved these changes

2018-11-23 11:57 UTC, merged